
server:
  port: 8020
spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://configurations:8000/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

springdoc:
  api-docs:
    path: "/cards/v3/api-docs/swagger-config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoint:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://eureka-servicediscovery:8001/eureka/"


info:
  app:
    name: cards
    description: "SmallBank cards service"
    version: "1.0.0"

logging:
  level:
    com:
      org:
        cards:
          cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

