

deploymentName: configurations-deployment
serviceName: configurations
appLabel: configurations
appName: configurations

replicaCount: 1

image:
  repository: kiranfegade19/configurations
  tag: 1.0.0

containerPort: 8000

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: false