global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'configurations'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configurations:8000' ]
  - job_name: 'eureka-servicediscovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eureka-servicediscovery:8001' ]
  - job_name: 'users'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'users:8010' ]
  - job_name: 'cards'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cards:8020' ]
  - job_name: 'cards1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cards1:8020' ]
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8002' ]


