pipeline {
    agent any

    tools {
        maven 'Maven 3.9.9'  // Referencing Maven tool
        jdk 'jdk-17.0.14.jdk'        // Referencing JDK 17
    }

    environment {
        DOCKER_IMAGE = "yourusername/${APP}:${BUILD_NUMBER}"
        HELM_RELEASE = "${APP}-release"
        ENV = "${ENV}"
    }
    stages {

    stage('Display JDK Path') {
                steps {
                    script {
                        //echo "JDK Path: ${tool name: 'jdk-17.0.14.jdk', type: 'JDK'}"
                        sh 'ls -ltr /bitnami/jenkins/home/tools/hudson.model.JDK/jdk-17.0.14.jdk/openlogic-openjdk-17.0.14+7-linux-x64/'
                    }
                }
            }

        stage('Build and Push Docker Images of Springboot Applications') {
            steps {
                script {
                // Define the list of application directories
                    def apps = ['cards', 'configurations', 'eureka-servicediscovery', 'gatewayserver', 'messages', 'users']

                    // Iterate over each application directory
                    apps.each { app ->
                        dir(app) {
                            // Execute commands within the application's directory
                            echo "Building ${app} now"
                            sh 'mvn clean install'
                            sh 'mvn compile jib:dockerBuild'
                            sh 'docker push yourusername/${app}:1.0.0'
//                             sh 'helm dependency build ./helm'
//                             sh 'helm upgrade --install ${app}-release ./helm --set image.tag=1.0.0'
                        }
                    }
                }
            }
        }
        stage('Build Helm Charts for all applications') {
            steps {
                script {

                    echo "Path-1: $PWD"

                    sh 'cd ./helm/environment/${ENV}'
                    echo "Path-2: $PWD"
                    sh 'helm dependencies build'

                    sh 'cd ../../side-car-charts/starters/'
                    echo "Path-3: $PWD"
                    sh 'startAll.sh'

                    sh 'cd ../../environment/'
                    echo "Path-4: $PWD"
                    sh 'helm install smallbank-${ENV} ${ENV}'
                }
            }
        }
    }
}
