

deploymentName: messages-deployment
serviceName: messages
appLabel: messages
appName: messages

replicaCount: 1

image:
  repository: kiranfegade19/messages
  tag: 1.0.0

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resourceserver_enabled: false
otel_enabled: false
kafka_enabled: true