

deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 2

image:
  repository: kiranfegade19/cards
  tag: 1.0.0

containerPort: 8020

service:
  type: ClusterIP
  port: 8020
  targetPort: 8020

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: false